version: 1.0.{build}
image:
- Visual Studio 2019

build:
  verbosity: minimal
  
dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  
test:
  # only assemblies to test
  assemblies:
    only:
      - '**\*.tests.dll'
